[files]
extend-exclude = [
    "benchmark/data/bench.yaml",
    "tests/yaml-test-suite/",
    "ruff.toml",
]

[default.extend-words]
# error: `BA` should be `BY`, `BE`
#    --> .\tests\test_loads.py:413:26
#     |
# 413 |          " 56enmleECcgggoBADs=\n"
#     |                          ^^
# error: `BA` should be `BY`, `BE`
#    --> .\tests\test_loads.py:426:37
#     |
# 426 |                      "56enmleECcgggoBADs=\n"}),
#     |                                     ^^
ba = "ba"