target-version = "py310"

line-length = 90

include = [
    "py-src/**.py",
    "py-src/**.pyi",
    "tests/**.py",
    "examples/**.py",
    "benchmark/**.py",
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]

[lint]
preview = true

allowed-confusables = [
    "’",
    "ס",
    "Α",
    "К",
]
select = ["ALL"]
ignore = [
    "D",
    "TD",
    "FIX",
    #______#
    "ANN401",
    "ISC004",
    #______#
    "CPY001",
    "ARG001",
    #______#
    "PLR2004",
    "PLR6201",
]

[lint.extend-per-file-ignores]
"examples/**.py" = [
    "INP001",
    "T201",
    "T203",
    "PLC3002",
]
"tests/**.py" = [
    "S101",
    "E501",
    "ERA001",
]
"tests/test_dumps.py" = [
    "DTZ01",
    "DTZ001",
]
"benchmark/run.py" = [
    "INP001",
    "PLC3002",
]

[lint.flake8-tidy-imports.banned-api]
"contextlib.suppress" = { msg = "Use `try-except-pass` instead" }