target-version = "py310"

line-length = 90

include = [
    "py-src/**.py",
    "py-src/**.pyi",
    "tests/**.py",
    "examples/**.py",
    "benchmark/**.py",
    "pyproject.toml",
    "README.md",
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]

[lint]
preview = true

allowed-confusables = [
    "’",
    "ס",
    "Α",
    "К",
]
select = ["ALL"]
ignore = [
    "ARG",     # Unused method argument
    "D",       # Docstring's
    ########
    "CPY001",  # Check copyright notices within Python files
    "S311",    # Force `random` -> `secrets`
    "ANN401",  # Check `typing.Any`
    "SIM105",  # Force `try-except-pass` -> `contextlib.suppress`
    "ISC004",  # Check for implicitly concatenated strings inside list, tuple, and set literals.
    #######
    "PLR6201", # Check for membership tests on list and tuple literals.
    ########
    "TC001",   # \
    "TC002",   #  ==> `typing.TYPE_CHECKING` block's
    "TC003",   # /
    "TC006",   # Add quotes to type expression in `typing.cast()`
]

[lint.extend-per-file-ignores]
"examples/**.py" = [
    "INP001",
    "T201",
    "T203",
    "PLC3002",
]
"tests/**.py" = [
    "S101",
    "E501",
    "ERA001",
]
"tests/test_dumps.py" = [
    "DTZ001", # Check for datetime instantiations that do not specify a timezone
    "FIX001", # Check for "FIXME" comments
    ########
    "TD001",  # Check that a TODO comment is labelled with "TODO"
    "TD003",  # Check that a TODO comment is associated with a link to a relevant issue or ticket
    "TD004",  # Check that a "TODO" tag is followed by a colon.
    "TD005",  # Check that a "TODO" tag contains a description of the issue following the tag itself.
]
"benchmark/**.py" = [
    "INP001",
    "PLC3002",
]

[lint.pylint]
max-args = 10

[lint.flake8-tidy-imports.banned-api]
"contextlib.suppress" = { msg = "Use `try-except-pass` instead" }
"__future__.annotations" = { msg = "Directly quote annotations instead" }