name: tool
description: Install and run a selected uv-based tool

inputs:
  tool:
    description: "zizmor, typos, rumdl"
    required: true
  python-version:
    description: "python version to use"
    required: false
    default: "3.13"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: "Install uv"
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }} # zizmor: ignore[cache-poisoning]
    - name: "Install and run selected tool"
      shell: bash
      env:
        TOOL: ${{ inputs.tool }}
      run: |
        case "$TOOL" in
          zizmor)
            uv pip install --group zizmor --system
            zizmor .github/
            ;;
          typos)
            uv pip install --group typos --system
            typos --config .typos.toml
            ;;
          rumdl)
            uv pip install --group rumdl --system
            rumdl check .
            ;;
          *)
            echo "Unsupported tool input: $TOOL"
            exit 1
            ;;
        esac
