name: CI

permissions: { }

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "scripts/"
  pull_request:
    paths-ignore:
      - "scripts/"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  wasm:
    # needs: [ tests, tests-alpine, cargo-fmt, cargo-clippy, zizmor, typos ]
    uses: ./.github/workflows/wasm.yml
