name: "macos"

on:
  workflow_call:

jobs:
  macos:
    name: "macos-latest / ${{ matrix.platform.target }}"
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - {
            # Intel Mac
            target: x86_64,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-build-args: "--features mimalloc"
          }
          - {
            # Apple Silicon M1-M4
            target: aarch64,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-build-args: "--features mimalloc"
          }
          - {
            # Universal binary (Intel + Apple Silicon)
            target: universal2,
            interpreter: "3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11",
            maturin-build-args: "--features mimalloc"
          }

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Build wheels"
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.platform.target }}
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }} # zizmor: ignore[cache-poisoning]
          args: >
            --release
            --out dist
            --interpreter ${{ matrix.platform.interpreter }}
            ${{ matrix.platform.maturin-build-args }}
            --compatibility pypi

      - name: "Upload wheels"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist
