name: "tests"

on:
  workflow_call:

jobs:
  tests:
    name: "${{ matrix.os }} / python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.13t",
          "3.14",
          "3.14t",
          "pypy3.11",
        ]
        os: [
          "ubuntu-latest",
          "windows-latest",
        ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        if: github.event_name == 'pull_request' && github.run_attempt == 1
        with:
          lookup-only: false # zizmor: ignore[cache-poisoning]
          shared-key: ${{ matrix.os }}-${{ matrix.python-version }}

      - name: "Create and activate .venv"
        shell: bash
        run: |
          uv venv .venv --python ${{ matrix.python-version }}
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo ".venv/Scripts" >> "$GITHUB_PATH"
            echo "PYO3_PYTHON=.venv/Scripts/python" >> "$GITHUB_ENV"
            echo "UV_LINK_MODE=copy" >> "$GITHUB_ENV"
          else
            echo ".venv/bin" >> "$GITHUB_PATH"
            echo "PYO3_PYTHON=.venv/bin/python3" >> "$GITHUB_ENV"
          fi

      - name: "Install dependencies"
        run: uv pip install --group ci

      - name: "Run maturin"
        run: maturin build --out wheel --features mimalloc

      - name: "Install built wheel"
        shell: bash
        run: uv pip install wheel/*.whl

      - name: "Run ruff"
        run: ruff check

      - name: "Run pytest"
        run: pytest tests/
